export const emoji = { 	
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f590.svg">' :':wait:',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f4a4.svg">' :':zzz:',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f494.svg">' :':brokenheart:',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/2764.svg">' :':heart:',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f60d.svg">' :':love:',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f3b5.svg">' :':music:',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f339.svg">' :'@->--',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f617.svg">' :':kiss:',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f608.svg">' :':devil:',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/2615.svg">' :':coffee:',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f37a.svg">' :':beer:',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f44e.svg">' :':no:',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f44d.svg">' :':yes:',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f910.svg">' :':-X',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f60e.svg">' :'8-)',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f618.svg">' :':kiss:',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f632.svg">' :'=-O',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f61b.svg">' :':-P',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f609.svg">' :';-)',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f61e.svg">' :':-(',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f601.svg">' :':-D',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f642.svg">' :':-)',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f620.svg">' :'>:-(',
    '<img class="simply" src="././helper/lib/emojione/assets/svg/1f607.svg">' :'O:-)'
}
